version: "3.8"

services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - db
    # environment:
    #   - DB_HOST=db
    #   - DB_PORT=5432
    #   - DB_USER=root
    #   - DB_PASSWORD=root
    #   - DB_NAME=mydb

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
